services:
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  sidekiq:
    build: ./backend-DairySense
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend-DairySense:/app

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DairySense2025
      POSTGRES_DB: Dados
      TZ: America/Sao_Paulo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "15433:5432"

  backend:
    build: ./backend-DairySense
    container_name: rails_api
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:DairySense2025@db:5432/Dados
      TZ: America/Sao_Paulo
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

    volumes:
      - ./backend-DairySense:/app/backend
    ports:
      - "3000:3000"

 # frontend:
  #  build: ./frontend-DayriSense
  #  container_name: react_app
  #  depends_on:
  #    - backend
  #  volumes:
  #    - ./frontend:/app
  #  ports:
  #    - "8080:3000"
  #  command: ["npm", "start"]

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:80"
    depends_on:
     # - frontend
      - backend